In [46]:
import numpy as np

matrix1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
matrix2 = np.array([[9,8,7],
        [6,5,4],
        [3,2,1]])

matrix_sum = np.add(matrix1,matrix2)
print("The Sum of the matrices \n\n{}  and \n\n{}  is \n\n{} ".format(matrix1,matrix2,matrix_sum))

The Sum of the matrices 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[9 8 7]
 [6 5 4]
 [3 2 1]]  is 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 


In [47]:
import numpy as np

matrix1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
matrix2 = np.array([[9,8,7],
        [6,5,4],
        [3,2,1]])

matrix_product = np.dot(matrix1,matrix2)
print("The Product of the matrices \n\n{}  and \n\n{}  is \n\n{} ".format(matrix1,matrix2,matrix_product))

The Product of the matrices 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[9 8 7]
 [6 5 4]
 [3 2 1]]  is 

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]] 


In [48]:
import numpy as np

matrix1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])


matrix_transpose = np.transpose(matrix1)
print("The Transpose of the matrix \n\n{} is \n\n{} ".format(matrix1,matrix_transpose))

The Transpose of the matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]] is 

[[1 4 7]
 [2 5 8]
 [3 6 9]] 


In [51]:
def words_sorter():
    
    user_input = input("Enter a string of words to sort them in alphabetical order: ")
    print()
    sorted_list = sorted(user_input.lower().split())
    print(' '.join(sorted_list))

words_sorter()

Enter a string of words to sort them in alphabetical order: hello my name is tony

hello is my name tony


In [52]:
def punctuation_remover():
    import string
    user_input = input("Enter the string from which you want to remove the punctuation: ")
    output = ''.join([i for i in user_input if i not in string.punctuation])
    return output

punctuation_remover()

Enter the string from which you want to remove the punctuation: Full-stack data science course is a live mentor-led job guaranteed certification program with a full-time one-year internship provided by iNeuron, in this course you will learn the entire stack required to work in the data science, data analytics, and big data domain, including machine learning, deep learning, computer vision NLP and Big data including MLOps and cloud infrastructure, along with real-time industry projects and product development with the iNeuron product development team, which will enable you to contribute on various levels.


'Fullstack data science course is a live mentorled job guaranteed certification program with a fulltime oneyear internship provided by iNeuron in this course you will learn the entire stack required to work in the data science data analytics and big data domain including machine learning deep learning computer vision NLP and Big data including MLOps and cloud infrastructure along with realtime industry projects and product development with the iNeuron product development team which will enable you to contribute on various levels'